name: Build and Publish Full Docker Image

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    permissions:
      contents: read
      packages: write
      id-token: write
    runs-on: ubuntu-latest
    env:
      ORGA_NAME: 'Sparx-Foundation'
      REPO_NAME: 'subscriber'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from tag
        id: extract_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.ORGA_NAME }}/${{ env.REPO_NAME }}:latest
            ghcr.io/${{ env.ORGA_NAME }}/${{ env.REPO_NAME }}:${{ env.VERSION }}
